// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Usuario struct {
	ID        int32
	Nombre    string
	Apellido  string
	Email     string
	Telefono  sql.NullString
	PagoAlDia sql.NullBool
	CreadoEn  sql.NullTime
}
